config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#top'

  resources :users, only: %i[index new create show edit update destroy]
  resources :posts, only: %i[index new create edit update destroy] do
    resource :like, only: %i[create destroy]
    resource :map,  only: %i[create show update]
  end

  resources :likes,    only: %i[index]
  resources :maps,     only: %i[index new create show update]
  resources :rankings, only: %i[index]

  get  '/login',                   to: 'sessions#new'
  get  '/auth/:provider/callback', to: 'sessions#twitter'
  post '/login',                   to: 'sessions#create'
  post '/logout',                  to: 'sessions#destroy'
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

PER = 5

class LikesController < ApplicationController
  before_action :authenticate_user, only: %i[create destroy]

  def index
    @posts = current_user.like_posts.order(created_at: :desc)
    @like_posts = @posts.page(params[:page])
                        .per(PER)
                        .order(created_at: :desc)
                        .includes(:user)
  end

  def create
    like = Like.new
    like.user_id = current_user.id
    like.post_id = params[:post_id]
    like.save
    @user = User.find(current_user.id)
    @post = Post.find(params[:post_id])
  end

  def destroy
    like = Like.find_by(post_id: params[:post_id], user_id: current_user)
    like.destroy
    @user = User.find(current_user.id)
    @post = Post.find(params[:post_id])
  end
end

app/views/likes/_like.html.erb
<% if user %>
  <% if !user.like_posts.include?(post) %>
    <div class="like">
      <%= link_to post_like_path(post_id: post.id), method: :post,
      id: "like-button", remote: true do %>
        <span class="fa fa-heart like-btn" id="<%= post.id %>"></span>
        <%= post.like_users.length %>
      <% end %>
    </div>
  <% else %>
    <div class="unlike">
      <%= link_to post_like_path(post_id: post.id), method: :delete,
        id: "like-button", remote: true do %>
        <span class="fa fa-heart like-btn-unlike" id="<%= post.id %>"></span>
        <%= post.like_users.length %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post, user: @user}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post, user: @user}) %>");

app/views/likes/index.html.erb
<div class="wrapper">
  <div class="posts-container">
    <div class="row">
      <% @like_posts .each do |post| %>
        <div class="col-md-offset-4 col-md-4 post-list-container text-left mt-4">
          <div class="post-list-card">
            <div class="post-user-image">
              <% if post.user.uid != nil %>
                <img src ="<%= post.user[:image_url] %>" >
              <% else %>
                <%= image_tag post.user.image.to_s %>
              <% end %>
            </div>
            <div class="post-user-name">
              <p><%= link_to "@"+"#{post.user.name}",user_path(post.user.id) %></p>
            </div>
            <p class="post-info">
              <%= post.user.created_at.strftime("%Y-%m-%d %H:%M") %>
            </p>
            <p class="post-title">
              店名：<%= post.store %>
            </p>
            <p class="post-title">
              品名：<%= post.title %>
            </p>
            <p class="post-title">
              住所：<%= post.prefecture.name if post.prefecture_id? %>
              <%= post.city %>
            </p>
            <p class="post-body">
              感想：<%= simple_format(post.description) %>
            </p>
            <h4>評価：<%= post.rate %>点</h4>

            <!--星評価-->
            <div class="post-star" id="star-rate-<%= post.id %>"></div>
            <script>
            $('#star-rate-<%= post.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= post.rate %>,
            });
            </script>
            <!--/星評価-->

            <div class="post-img">
              <%= image_tag post.image.to_s %>
            </div>

            <div class="text-center post-map">
              <%= link_to post_map_path(post_id: post.id), method: :post do %>
                <button class="btn btn-primary">周辺地図を表示</button>
              <% end %>
            </div>

          </div>
        </div>
      <% end %>
    </div>
    <div class="paginate text-center">
      <%= paginate @like_posts %>
    </div>
  </div>
</div>