config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#top'

  resources :users, only: %i[index new create show edit update destroy]
  resources :posts, only: %i[index new create edit update destroy] do
    resource :like, only: %i[create destroy]
    resource :map,  only: %i[create show update]
  end

  resources :likes,    only: %i[index]
  resources :maps,     only: %i[index new create show update]
  resources :rankings, only: %i[index]

  get  '/login',                   to: 'sessions#new'
  get  '/auth/:provider/callback', to: 'sessions#twitter'
  post '/login',                   to: 'sessions#create'
  post '/logout',                  to: 'sessions#destroy'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save :email_downcase, unless: :uid?

  validates :name, presence: true, unless: :uid?, length: { maximum: 15 }, uniqueness: true
  validates :introduction, unless: :uid?, length: { maximum: 100 }
  # メールアドレスは~@~.~の形で記入
  validates :email, unless: :uid?,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  # 8~32文字で英数字を両方１文字以上で記入
  validates :password,  on: :create, unless: :uid?,
                        format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,32}+\z/i }

  has_secure_password validations: false

  mount_uploader :image, ImageUploader

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: 'post'

  # ツイッター認証機能
  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    image = auth[:info][:image]
    introduction = auth[:info][:description]

    find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.image_url = image
      user.introduction = introduction
    end
  end

  def email_downcase
    email.downcase!
  end

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA256.hexdigest(token.to_s)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

PER = 5

class UsersController < ApplicationController
  before_action :authenticate_user, only: %i[show edit update]
  before_action :ensure_correct_user, only: %i[update edit]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id]).includes(:user, :likes, :like_users)
    @user_posts = @posts.page(params[:page]).per(PER).order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find_by(id: current_user.id)
    if @user.update(user_params)
      redirect_to user_path, success: '変更が完了しました'
    else
      flash.now[:danger] = '変更に失敗しました'
      render :edit
    end
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @post = Post.where(user_id: params[:id])

    # 管理人のみが削除可能
    if current_user.id == 1
      if @user.destroy
        @post.delete_all
        redirect_to root_path, success: 'ユーザーを削除しました'
      else
        flash.now[:danger] = 'ユーザーの削除に失敗しました'
        render :edit
      end
    else
      redirect_to user_path(current_user.id), danger: 'あなたに権限はありません'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :image, :introduction)
  end

  def log_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:user_remember_token] = remember_token
    user.update!(remember_token: User.encrypt(remember_token))
    @current_user = user
  end
end

app/views/users/edit.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 user-edit-container">
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :"名前 ※15文字以内" %>
            <%= f.text_area :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :"自己紹介 ※100文字以内" %>
            <%= f.text_area :introduction, rows:5, class: "form-control" %>
          </div>

          <!-- ツイッターユーザーは画像を変更させない -->
          <% if @user.uid == nil %>
            <div class="form-group">
              <%= f.label :"画像" %>
              <%= f.file_field :image %>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.submit '更新', class: "btn btn-block btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="wrapper">
  <div class="users-container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6 users-list-container">
      <% @users.each do |user| %>
          <div class="users-list-card col-md-4">
            <div class="user-image">
              <% if user.uid != nil %>
                <img src ="<%= user[:image_url] %>" >
              <% else %>
                <%= image_tag user.image.to_s %>
              <% end %>
            </div>
            <p><%= link_to "#{user.name}",user_path(user.id) %></p>
          </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">新規登録</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, '名前 ※必須  15文字以内' %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :email, "メールアドレス ※必須" %>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :image, "プロフィール画像  ※任意" %>
            <%= f.file_field :image %>
          </div>
          <div class="form-group">
            <%= f.label :password, "パスワード ※必須  8~32文字で英数字" %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          <%= f.submit "登録",class: "btn btn-block btn-success" %>
        <% end %>

        <div class="text-center"><h4>or</h4></div>

        <div class="top-login text-center twitter-login">
          <%= link_to " Twitterアカウントでログイン", '/auth/twitter', class: "btn fab fa-twitter btn-primary" %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 user-contents-container text-center">
        <h2><%= @user.name %></h2>
        <div class="introduction"><%= simple_format(@user.introduction) %></div>
        <div class="user-image">
          <% if @user.uid != nil %>
            <img src ="<%= @user[:image_url] %>" >
          <% else %>
            <%= image_tag @user.image.to_s %>
          <% end %>
        </div>
        <% if current_user.id == @user.id %>
          <%= link_to "プロフィール編集", edit_user_path %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper">
  <div class="col-md-offset-4 col-md-4">
    <h2>[<%= @user.name %>さんの投稿]</h2>
  </div>
  <div class="posts-container">
    <div class="row">
      <% @user_posts .each do |post| %>
        <div class="col-md-offset-4 col-md-4 post-list-container text-left mt-4">
          <div class="post-list-card">
            <div class="post-user-image">
              <% if post.user.uid != nil %>
                <img src ="<%= post.user[:image_url] %>" >
              <% else %>
                <%= image_tag post.user.image.to_s %>
              <% end %>
            </div>
            <div class="post-user-name">
              <p><%= link_to "@"+"#{post.user.name}",user_path(post.user.id) %></p>
            </div>
            <p class="post-info">
              <%= post.user.created_at.strftime("%Y-%m-%d %H:%M") %>
            </p>
            <p class="post-title">
              店名：<%= post.store %>
            </p>
            <p class="post-title">
              品名：<%= post.title %>
            </p>
            <p class="post-title">
              住所：<%= post.prefecture.name if post.prefecture_id? %>
              <%= post.city %>
            </p>
            <p class="post-body">
              感想：<%= simple_format(post.description) %>
            </p>
            <h4>評価：<%= post.rate %>点</h4>

            <!--星評価-->
            <div class="post-star" id="star-rate-<%= post.id %>"></div>
            <script>
            $('#star-rate-<%= post.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn :  '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= post.rate %>,
            });
            </script>
            <!--星評価-->

            <div class="post-img">
              <%= image_tag post.image.to_s %>
            </div>

            <div class="unlike">
              <p class="fa fa-heart like-btn-unlike">
                <%= post.like_users.length %>
              </p>
            </div>

            <div class="text-center post-map">
              <%= link_to post_map_path(post_id: post.id), method: :post do %>
                <button class="btn btn-primary">周辺地図を表示</button>
              <% end %>
            </div>

            <!-- 編集機能 -->
            <div class="text-right">
              <% if current_user.id == post.user_id %>
              <%= link_to "削除", post_path(post.id) ,method: :delete,
              data: {confirm: '本当に削除してもよろしいですか？'} %>
              <%= link_to "編集", edit_post_path(post.id) %>
              <% end %>
            </div>

          </div>
        </div>
      <% end %>
    </div>
    <div class="paginate text-center">
      <%= paginate @user_posts %>
    </div>
  </div>
</div>

<!-- 管理人のみ削除可能 -->
<div class="text-center">
  <% if current_user.id == 4 %>
  <p>※管理人コマンド</p>
  <%= link_to "ユーザーを削除", user_path(@user.id) ,method: :delete,data: {confirm: '本当に削除しても よろしいですか？'} %>
  <% end %>
</div>