config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#top'

  resources :users, only: %i[index new create show edit update destroy]
  resources :posts, only: %i[index new create edit update destroy] do
    resource :like, only: %i[create destroy]
    resource :map,  only: %i[create show update]
  end

  resources :likes,    only: %i[index]
  resources :maps,     only: %i[index new create show update]
  resources :rankings, only: %i[index]

  get  '/login',                   to: 'sessions#new'
  get  '/auth/:provider/callback', to: 'sessions#twitter'
  post '/login',                   to: 'sessions#create'
  post '/logout',                  to: 'sessions#destroy'
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiMMy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=360,initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- googleフォント -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Economica:700 rel="stylesheet">

  </head>
<!DOCTYPE html>
  <body>
    <nav class="navbar navbar-default navbar-expand-md navbar-fixed-top">
      <div class="nav-container nav">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "BiMMy", root_path, id: "logo" %></li>
        </ul>

        <script>
              $("#logo").hover(
          function(){
            $(this).animate({
              'font-size':'2.1em'
            }, 300);
          },
          function(){
           $(this).animate({
              'font-size':'2em'
            }, 300);
           });
        </script>

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <div class="collapse navbar-collapse" id="site-menu">
          <ul class="nav navbar-nav navbar-right">

            <% if current_user %>
              <li>
                <%= link_to "人気投稿", rankings_path, class:"fas fa-crown font-weight-normal" %>
              </li>
              <li>
                <%= link_to "Myいいね", likes_path, class:"fa fa-heart" %>
              </li>
              <li>
                <%= link_to "投稿一覧", posts_path, class:"fa fa-comments" %>
              </li>
              <li>
                <%= link_to "登録者一覧", users_path, class:"fas fa-user" %>
              </li>
              <li>
                <%= link_to "投稿する", new_post_path, class:"fas fa-edit" %>
              </li>
              <li>
                <%= link_to "ログアウト", logout_path, method:"post",
                    class:"fas fa-sign-out-alt" %>
              </li>
              <li >
                <div class="current-user-image col-md-12">
                  <% if current_user.uid != nil %>
                    <img src ="<%= current_user[:image_url]%>" >
                  <% else %>
                    <%= image_tag current_user.image.to_s %>
                  <% end %>
                  <%= link_to "#{current_user.name}",user_path(current_user.id) %>
                </div>
              </li>
            <% end %>

            <% if !current_user %>
              <li>
                <%= link_to "投稿一覧", posts_path, class:"fa fa-comments" %>
              </li>
              <li>
                <%= link_to "登録者一覧", users_path, class:"fas fa-user" %>
              </li>
              <li>
                <%= link_to "新規登録",new_user_path, class:"fas fa-user-edit" %>
              </li>
              <li>
                <%= link_to "ログイン",login_path, class:"fas fa-sign-in-alt" %>
              </li>
            <% end %>

          </ul>
        </div>
      </div>

      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
      <% end %>
      <script>
        $(function () {
          $(".alert").fadeOut(4000);
        });
      </script>

    </nav>


    <%= yield %>



    <p class="pagetop"><a href="#wrap">PAGE<br>TOP</a></p>

  </body>

  <footer id="footer" class="bg-light flex-column justify-content-center">
    <p>© 2019 DAICHI HOSHINA All Rights Reserved.</p>
  </footer>

</html>